business:
  base_currency: USD
  company_name: Mr.Clean Insurance Platform
  default_expense_ratio: 0.05
  default_profit_margin: 0.15
  regulatory_jurisdiction: US
data_sources:
  alpha_vantage:
    connection_params:
      api_key: ${ALPHA_VANTAGE_KEY}
      base_url: https://www.alphavantage.co/query
    fallback_enabled: true
    refresh_interval_hours: 1
    retry_count: 3
    timeout_seconds: 30
    type: api
  fred_api:
    connection_params:
      api_key: ${FRED_API_KEY}
      base_url: https://api.stlouisfed.org/fred
      format: json
    fallback_enabled: true
    refresh_interval_hours: 24
    retry_count: 3
    timeout_seconds: 30
    type: api
  soa_mortality_tables:
    connection_params:
      data_path: data/mortality_tables
      table_version: 2017_CSO
    fallback_enabled: true
    refresh_interval_hours: 8760
    type: file
models:
  economic_forecasting:
    auto_retrain: true
    parameters:
      dropout_rate: 0.2
      epochs: 100
      hidden_layers:
      - 64
      - 32
      - 16
    training_schedule: weekly
    type: neural_network
    validation_threshold: 0.75
  lapse_prediction:
    auto_retrain: true
    parameters:
      max_depth: 10
      n_estimators: 200
      random_state: 42
    training_schedule: quarterly
    type: random_forest
    validation_threshold: 0.8
  mortality_enhancement:
    auto_retrain: true
    feature_columns:
    - age
    - gender
    - smoker
    - bmi
    - medical_history
    parameters:
      learning_rate: 0.1
      max_depth: 6
      n_estimators: 500
      random_state: 42
    training_schedule: monthly
    type: xgboost
    validation_threshold: 0.85
system:
  data_storage_path: data
  debug_mode: true
  environment: development
  log_storage_path: logs
  model_storage_path: models
  version: 1.0.0
